name: Docker Build CI

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

env:
  GIT_BRANCH_NAME: "${{ github.ref }}" # ${GIT_BRANCH_NAME##*/}
  GIT_REPOSITORY_NAME: "${{ github.event.repository.name }}"
  DOCKER_REPOSITORY: mvladislav

  BUILD_DATE: 2021

  PROJECT_NAME: vm_recon
  ENV_MODE: "${{ contains(github.ref, 'main') && 'PROD' || 'KONS' }}"
  VERSION: "0.0.1"
  LOGGING_LEVEL: "${{ contains(github.ref, 'main') && 'INFO' || 'DEBUG' }}"
  LOGGING_VERBOSE: "${{ contains(github.ref, 'main') && 2 || 3 }}"

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # BUILD
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      - name: create .env
        run: echo "PROJECT_NAME=${PROJECT_NAME}\nENV_MODE=${ENV_MODE}\nVERSION=${VERSION}\nLOGGING_LEVEL=${LOGGING_LEVEL}\nLOGGING_VERBOSE=${LOGGING_VERBOSE}" > .env

      - name: Build the Docker image
        run: DOCKER_BUILDKIT=1 docker-compose --project-name ${PROJECT_NAME} build
